version: "2"
services:

  uwsgi:
    build:
      context: .
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    command: "uwsgi --ini /var/www/config_uwsgi/uwsgi.ini"

  nginx:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    links:
      - uwsgi
    command: "nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"
