version: "2"
services:

  uwsgi:
    image: "yamasy1549/chat_platform_doteni_uwsgi"
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "uwsgi"

  nginx:
    image: "yamasy1549/chat_platform_doteni_nginx"
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
