version: "3"
services:

  uwsgi:
    build: .
    volumes:
      - .:/var/www/
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx_log:/var/log/nginx
      - ./flaskr/static:/var/static
    links:
      - uwsgi
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
