DEBUG = True
SQLALCHEMY_DATABASE_FILE = "flaskr.db"
SQLALCHEMY_DATABASE_URI = "sqlite:///{}".format(SQLALCHEMY_DATABASE_FILE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "secret key"
THREADED = True
